import sys

while True:
	teste = raw_input()
	if not teste:
		break
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc01passadis/cvc01passadis-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc02lab/cvc02lab-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc03despatx/cvc03despatx-pano14-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc04passadis/cvc04passadis-pano22-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/etse01entrada/etse01entrada-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/etse02passadis/etse02passadis-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia01robot/iiia01robot-pano27-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia02lab/iiia02lab-pano11-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia04actes/iiia04actes-pano14-full.pngs HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia05passadis/iiia05passadis-pano20-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia06biblioteca/iiia06biblioteca-pano25-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia07biblioteca/iiia07biblioteca-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia08lab/iiia08lab-pano19-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia09power/iiia09power-pano10-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia10backdoor/iiia10backdoor-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia11menjador/iiia11menjador-pano19-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia12menjador/iiia12menjador-pano20-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia13entrada/iiia13entrada-pano21-full.png HARRIS SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc01passadis/cvc01passadis-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc02lab/cvc02lab-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc03despatx/cvc03despatx-pano14-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/cvc04passadis/cvc04passadis-pano22-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/etse01entrada/etse01entrada-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/etse02passadis/etse02passadis-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia01robot/iiia01robot-pano27-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia02lab/iiia02lab-pano11-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia04actes/iiia04actes-pano14-full.pngs MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia05passadis/iiia05passadis-pano20-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia06biblioteca/iiia06biblioteca-pano25-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia07biblioteca/iiia07biblioteca-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia08lab/iiia08lab-pano19-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia09power/iiia09power-pano10-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia10backdoor/iiia10backdoor-pano21-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia11menjador/iiia11menjador-pano19-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia12menjador/iiia12menjador-pano20-full.png MSER SIFT'
	print './compara '+teste + ' /home/guardezi/Documents/mestrado/programas/dataset/iiia13entrada/iiia13entrada-pano21-full.png MSER SIFT'
